# Generated by Django 6.0.2 on 2026-04-30 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_address_userprofile_farm_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='admin_approved',
            field=models.BooleanField(default=True),
        ),
    ]
