# Generated by Django 6.0.2 on 2026-03-05 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='producer',
            old_name='description',
            new_name='bio',
        ),
        migrations.RemoveField(
            model_name='producer',
            name='farm_name',
        ),
        migrations.AddField(
            model_name='producer',
            name='display_name',
            field=models.CharField(default='Producer', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producer',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='producer',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='producer',
            name='location',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='producer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='producer', to=settings.AUTH_USER_MODEL),
        ),
    ]
