# Generated by Django 6.0.2 on 2026-03-26 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0002_rename_description_producer_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producer',
            name='postcode',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
