# Generated by Django 6.0.2 on 2026-04-06 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0003_producer_postcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='producer',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producer',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
