# Generated by Django 6.0.2 on 2026-03-26 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0003_producerorder_orderitem_producer_order'),
        ('producers', '0003_producer_postcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='fulfilment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='producer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='producers.producer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('partially_fulfilled', 'Partially Fulfilled'), ('cancelled', 'Cancelled'), ('fulfilled', 'Fulfilled')], default='pending', max_length=30),
        ),
    ]
