# Generated by Django 6.0.2 on 2026-04-06 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0004_orderitem_fulfilment_status_orderitem_producer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
