# Generated by Django 6.0.2 on 2026-03-18 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_available_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_percent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='section',
            field=models.CharField(choices=[('seasonal', 'Seasonal Items'), ('discounted', 'Discounted Items'), ('all', 'All Items')], default='all', max_length=20),
        ),
    ]
