# Generated by Django 6.0.2 on 2026-03-25 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_discount_percent_product_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='availability_mode',
            field=models.CharField(choices=[('seasonal', 'Seasonal'), ('year_round', 'Available Year-Round'), ('unavailable', 'Unavailable')], default='year_round', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='season_end_month',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='season_start_month',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], null=True),
        ),
    ]
