# Generated by Django 6.0.2 on 2026-03-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_discount_percent_product_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('vegetables', 'Vegetables'), ('dairy', 'Dairy Products'), ('bakery', 'Bakery Goods'), ('preserves', 'Preserves'), ('seasonal_specialities', 'Seasonal Specialities')], default='vegetables', max_length=30),
        ),
    ]
