# Generated by Django 6.0.2 on 2026-03-25 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('vegetables', 'Vegetables'), ('dairy', 'Dairy Products'), ('bakery', 'Bakery Goods'), ('preserves', 'Preserves'), ('fruits', 'Fruits'), ('seasonal_specialities', 'Seasonal Specialities')], default='vegetables', max_length=30),
        ),
    ]
