# Generated by Django 6.0.2 on 2026-03-25 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('each', 'Each'), ('g', 'Grams (g)'), ('kg', 'Kilograms (kg)'), ('ml', 'Millilitres (ml)'), ('l', 'Litres (l)'), ('pack', 'Pack')], default='each', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_value',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Example: 500 for 500g, 1 for 1kg, 6 for pack of 6', max_digits=8),
        ),
    ]
