# Generated by Django 6.0.2 on 2026-03-26 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_best_before_date_product_is_surplus_and_more'),
        ('products', '0006_product_unit_product_unit_value'),
    ]

    operations = [
    ]
