# Generated by Django 6.0.2 on 2026-04-16 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ai_action',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='ai_colour_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ai_explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ai_fresh_probability',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ai_grade',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='product',
            name='ai_last_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ai_predicted_label',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='ai_ripeness_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ai_rotten_probability',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ai_size_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
