# Generated by Django 6.0.2 on 2026-05-06 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_allergen_info'),
        ('products', '0011_product_low_stock_threshold_stockalert'),
    ]

    operations = [
    ]
